In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn as sklearn

In [3]:
train = pd.read_csv('./extracted/train.csv')
test = pd.read_csv('./extracted/test.csv')

In [4]:
train.head()

,QuoteNumber,Original_Quote_Date,QuoteConversion_Flag,Field6,Field7,Field8,Field9,Field10,Field11,Field12,...,GeographicField59A,GeographicField59B,GeographicField60A,GeographicField60B,GeographicField61A,GeographicField61B,GeographicField62A,GeographicField62B,GeographicField63,GeographicField64
0,1,2013-08-16,0,B,23,0.9403,0.0006,965,1.0200,N,...,9,9,-1,8,-1,18,-1,10,N,CA
1,2,2014-04-22,0,F,7,1.0006,0.0040,548,1.2433,N,...,10,10,-1,11,-1,17,-1,20,N,NJ
2,4,2014-08-25,0,F,7,1.0006,0.0040,548,1.2433,N,...,15,18,-1,21,-1,11,-1,8,N,NJ
3,6,2013-04-15,0,J,10,0.9769,0.0004,"1,165",1.2665,N,...,6,5,-1,10,-1,9,-1,21,N,TX
4,8,2014-01-25,0,E,23,0.9472,0.0006,"1,487",1.3045,N,...,18,22,-1,10,-1,11,-1,12,N,IL

In [10]:
train.keys()

Index([u'QuoteNumber', u'Original_Quote_Date', u'QuoteConversion_Flag',
       u'Field6', u'Field7', u'Field8', u'Field9', u'Field10', u'Field11',
       u'Field12',
       ...
       u'GeographicField59A', u'GeographicField59B', u'GeographicField60A',
       u'GeographicField60B', u'GeographicField61A', u'GeographicField61B',
       u'GeographicField62A', u'GeographicField62B', u'GeographicField63',
       u'GeographicField64'],
      dtype='object', length=299)